# Generated by Django 4.1.4 on 2022-12-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dummy_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Animeviews", new_name="Anime",),
    ]
